"""Pinned Hermes-informed provider presets used by Sift Profile.

This module is data-only on purpose. Protocol drivers consume resolved
profiles; they do not own provider catalog decisions.
"""

from typing import Any

HERMES_COMMIT_SHA = "bb6a4d2a57f3f239a2a6d74cb2dec9534a20e607"

MODEL_PROVIDER_PRESETS: list[dict[str, Any]] = [
    {
        "profile": {
            "name": "mock",
            "display_name": "Mock Runtime",
            "adapter": "mock",
            "default_base_url": "",
            "default_model": "mock-runtime",
            "api_mode": "mock",
            "protocol_driver": "MockRuntimeModelProvider",
            "exposure_tier": "hidden",
            "supports_model_listing": False,
            "description": "Local deterministic runtime for development.",
            "requires_api_key": False,
            "status": "development",
            "is_advanced": True,
        },
    },
    {
        "profile": {
            "name": "openai",
            "display_name": "OpenAI",
            "adapter": "openai_compatible",
            "default_base_url": "https://api.openai.com/v1",
            "default_model": "gpt-5.5",
            "api_mode": "chat_completions",
            "protocol_driver": "ChatCompletionsDriver",
            "exposure_tier": "plannedStable",
            "description": "OpenAI API via the OpenAI-compatible chat adapter.",
        },
        "aliases": ("openai_responses",),
    },
    {
        "profile": {
            "name": "deepseek",
            "display_name": "DeepSeek",
            "adapter": "openai_compatible",
            "default_base_url": "https://api.deepseek.com/v1",
            "default_model": "deepseek-chat",
            "api_mode": "chat_completions",
            "protocol_driver": "ChatCompletionsDriver",
            "hermes_plugin_path": "plugins/model-providers/deepseek/__init__.py",
            "exposure_tier": "plannedStable",
            "description": "DeepSeek via OpenAI-compatible chat completions.",
        },
    },
    {
        "profile": {
            "name": "openrouter",
            "display_name": "OpenRouter",
            "adapter": "openai_compatible",
            "default_base_url": "https://openrouter.ai/api/v1",
            "default_model": "openai/gpt-5.5",
            "api_mode": "chat_completions",
            "protocol_driver": "ChatCompletionsDriver",
            "hermes_plugin_path": "plugins/model-providers/openrouter/__init__.py",
            "exposure_tier": "plannedStable",
            "description": "OpenRouter aggregator via OpenAI-compatible chat completions.",
        },
    },
    {
        "profile": {
            "name": "nous",
            "display_name": "Nous",
            "adapter": "openai_compatible",
            "default_base_url": "https://inference-api.nousresearch.com/v1",
            "default_model": "Hermes-4-405B",
            "api_mode": "chat_completions",
            "protocol_driver": "ChatCompletionsDriver",
            "hermes_plugin_path": "plugins/model-providers/nous/__init__.py",
            "exposure_tier": "plannedStable",
            "description": "Nous Research inference endpoint.",
        },
    },
    {
        "profile": {
            "name": "kimi",
            "display_name": "Kimi",
            "adapter": "openai_compatible",
            "default_base_url": "https://api.moonshot.ai/v1",
            "default_model": "kimi-k2-0711-preview",
            "api_mode": "chat_completions",
            "protocol_driver": "ChatCompletionsDriver",
            "hermes_plugin_path": "plugins/model-providers/kimi-coding/__init__.py",
            "exposure_tier": "plannedStable",
            "description": "Moonshot Kimi via OpenAI-compatible chat completions.",
        },
    },
    {
        "profile": {
            "name": "custom",
            "display_name": "Custom OpenAI-compatible",
            "adapter": "openai_compatible",
            "default_base_url": "https://api.openai.com/v1",
            "default_model": "gpt-5.5",
            "api_mode": "chat_completions",
            "protocol_driver": "ChatCompletionsDriver",
            "hermes_plugin_path": "plugins/model-providers/custom/__init__.py",
            "exposure_tier": "plannedStable",
            "description": "Custom, local, or self-hosted OpenAI-compatible endpoint.",
            "is_advanced": True,
        },
        "aliases": ("sift_runtime", "hermes_lite", "openai_compatible"),
    },
    {
        "profile": {
            "name": "alibaba",
            "display_name": "Alibaba DashScope",
            "adapter": "openai_compatible",
            "default_base_url": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
            "default_model": "qwen3-coder-plus",
            "hermes_plugin_path": "plugins/model-providers/alibaba/__init__.py",
            "exposure_tier": "advanced",
            "description": "Alibaba DashScope OpenAI-compatible endpoint.",
        },
    },
    {
        "profile": {
            "name": "alibaba-coding-plan",
            "display_name": "Alibaba Coding Plan",
            "adapter": "openai_compatible",
            "default_base_url": "https://coding-intl.dashscope.aliyuncs.com/v1",
            "default_model": "qwen3-coder-plus",
            "hermes_plugin_path": "plugins/model-providers/alibaba-coding-plan/__init__.py",
            "exposure_tier": "advanced",
            "description": "Alibaba Cloud Coding Plan OpenAI-compatible endpoint.",
        },
    },
    {
        "profile": {
            "name": "anthropic",
            "display_name": "Anthropic",
            "adapter": "anthropic_messages",
            "default_base_url": "https://api.anthropic.com",
            "default_model": "claude-haiku-4-5-20251001",
            "api_mode": "anthropic_messages",
            "protocol_driver": "AnthropicMessagesDriver",
            "hermes_plugin_path": "plugins/model-providers/anthropic/__init__.py",
            "exposure_tier": "plannedStable",
            "description": "Claude native Messages API provider.",
        },
    },
    {
        "profile": {
            "name": "arcee",
            "display_name": "Arcee AI",
            "adapter": "openai_compatible",
            "default_base_url": "https://api.arcee.ai/api/v1",
            "default_model": "auto",
            "hermes_plugin_path": "plugins/model-providers/arcee/__init__.py",
            "exposure_tier": "advanced",
            "description": "Arcee AI OpenAI-compatible endpoint.",
        },
    },
    {
        "profile": {
            "name": "azure-foundry",
            "display_name": "Microsoft Foundry",
            "adapter": "openai_compatible",
            "default_base_url": "",
            "default_model": "",
            "hermes_plugin_path": "plugins/model-providers/azure-foundry/__init__.py",
            "exposure_tier": "advanced",
            "description": "Azure Foundry OpenAI-compatible endpoint; provide your resource URL.",
            "supports_model_listing": False,
        },
    },
    {
        "profile": {
            "name": "gemini",
            "display_name": "Google Gemini",
            "adapter": "gemini",
            "default_base_url": "https://generativelanguage.googleapis.com/v1beta",
            "default_model": "gemini-3.5-flash",
            "api_mode": "gemini",
            "protocol_driver": "GeminiDriver",
            "hermes_plugin_path": "plugins/model-providers/gemini/__init__.py",
            "exposure_tier": "plannedStable",
            "description": "Google Gemini native API provider.",
        },
    },
    {
        "profile": {
            "name": "gmi",
            "display_name": "GMI Cloud",
            "adapter": "openai_compatible",
            "default_base_url": "https://api.gmi-serving.com/v1",
            "default_model": "google/gemini-3.1-flash-lite-preview",
            "hermes_plugin_path": "plugins/model-providers/gmi/__init__.py",
            "exposure_tier": "advanced",
            "description": "GMI Cloud OpenAI-compatible endpoint.",
        },
    },
    {
        "profile": {
            "name": "huggingface",
            "display_name": "HuggingFace",
            "adapter": "openai_compatible",
            "default_base_url": "https://router.huggingface.co/v1",
            "default_model": "openai/gpt-oss-120b",
            "hermes_plugin_path": "plugins/model-providers/huggingface/__init__.py",
            "exposure_tier": "advanced",
            "description": "HuggingFace Inference Providers router.",
        },
    },
    {
        "profile": {
            "name": "kilocode",
            "display_name": "Kilo Code",
            "adapter": "openai_compatible",
            "default_base_url": "https://api.kilo.ai/api/gateway",
            "default_model": "google/gemini-3-flash-preview",
            "hermes_plugin_path": "plugins/model-providers/kilocode/__init__.py",
            "exposure_tier": "advanced",
            "description": "Kilo Code OpenAI-compatible gateway.",
        },
    },
    {
        "profile": {
            "name": "kimi-coding",
            "display_name": "Kimi Coding",
            "adapter": "openai_compatible",
            "default_base_url": "https://api.moonshot.ai/v1",
            "default_model": "kimi-k2-turbo-preview",
            "hermes_plugin_path": "plugins/model-providers/kimi-coding/__init__.py",
            "exposure_tier": "plannedStable",
            "description": "Moonshot Kimi Coding OpenAI-compatible endpoint.",
        },
    },
    {
        "profile": {
            "name": "minimax",
            "display_name": "MiniMax",
            "adapter": "anthropic_messages",
            "default_base_url": "https://api.minimax.io/anthropic",
            "default_model": "MiniMax-M3",
            "api_mode": "anthropic_messages",
            "protocol_driver": "AnthropicMessagesDriver",
            "hermes_plugin_path": "plugins/model-providers/minimax/__init__.py",
            "exposure_tier": "advanced",
            "description": "MiniMax Anthropic-compatible Messages endpoint.",
        },
    },
    {
        "profile": {
            "name": "novita",
            "display_name": "NovitaAI",
            "adapter": "openai_compatible",
            "default_base_url": "https://api.novita.ai/openai/v1",
            "default_model": "deepseek/deepseek-v3-0324",
            "hermes_plugin_path": "plugins/model-providers/novita/__init__.py",
            "exposure_tier": "advanced",
            "description": "NovitaAI OpenAI-compatible endpoint.",
        },
    },
    {
        "profile": {
            "name": "nvidia",
            "display_name": "NVIDIA NIM",
            "adapter": "openai_compatible",
            "default_base_url": "https://integrate.api.nvidia.com/v1",
            "default_model": "nvidia/llama-3.3-nemotron-super-49b-v1",
            "hermes_plugin_path": "plugins/model-providers/nvidia/__init__.py",
            "exposure_tier": "advanced",
            "description": "NVIDIA NIM OpenAI-compatible endpoint.",
        },
    },
    {
        "profile": {
            "name": "ollama-cloud",
            "display_name": "Ollama Cloud",
            "adapter": "openai_compatible",
            "default_base_url": "https://ollama.com/v1",
            "default_model": "gpt-oss:120b",
            "hermes_plugin_path": "plugins/model-providers/ollama-cloud/__init__.py",
            "exposure_tier": "advanced",
            "description": "Ollama Cloud OpenAI-compatible endpoint.",
        },
    },
    {
        "profile": {
            "name": "opencode-zen",
            "display_name": "OpenCode Zen",
            "adapter": "openai_compatible",
            "default_base_url": "https://opencode.ai/zen/v1",
            "default_model": "gemini-3-flash",
            "hermes_plugin_path": "plugins/model-providers/opencode-zen/__init__.py",
            "exposure_tier": "advanced",
            "description": "OpenCode Zen OpenAI-compatible endpoint.",
        },
    },
    {
        "profile": {
            "name": "stepfun",
            "display_name": "StepFun",
            "adapter": "openai_compatible",
            "default_base_url": "https://api.stepfun.ai/step_plan/v1",
            "default_model": "step-3.5-flash",
            "hermes_plugin_path": "plugins/model-providers/stepfun/__init__.py",
            "exposure_tier": "advanced",
            "description": "StepFun Step Plan OpenAI-compatible endpoint.",
        },
    },
    {
        "profile": {
            "name": "xiaomi",
            "display_name": "Xiaomi MiMo",
            "adapter": "openai_compatible",
            "default_base_url": "https://api.xiaomimimo.com/v1",
            "default_model": "mimo-v1",
            "hermes_plugin_path": "plugins/model-providers/xiaomi/__init__.py",
            "exposure_tier": "advanced",
            "description": "Xiaomi MiMo OpenAI-compatible endpoint.",
        },
    },
    {
        "profile": {
            "name": "zai",
            "display_name": "Z.AI / GLM",
            "adapter": "openai_compatible",
            "default_base_url": "https://api.z.ai/api/paas/v4",
            "default_model": "glm-4.5-flash",
            "hermes_plugin_path": "plugins/model-providers/zai/__init__.py",
            "exposure_tier": "advanced",
            "description": "Z.AI / GLM OpenAI-compatible endpoint.",
        },
    },
]
